// Generated by scripts/generate-db-types.py. Do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      activity: {
        Row: {
          id: number;
          project_id: string | null;
          entity_type: string;
          entity_id: string | null;
          actor_id: string | null;
          action: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          project_id?: string | null;
          entity_type: string;
          entity_id?: string | null;
          actor_id?: string | null;
          action: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          project_id?: string | null;
          entity_type?: string;
          entity_id?: string | null;
          actor_id?: string | null;
          action?: string;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "activity_actor_id_fkey"; columns: ["actor_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "activity_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] }
        ];
      };
      article_tags: {
        Row: {
          article_id: string;
          tag_id: string;
        };
        Insert: {
          article_id: string;
          tag_id: string;
        };
        Update: {
          article_id?: string;
          tag_id?: string;
        };
        Relationships: [
          { foreignKeyName: "article_tags_article_id_fkey"; columns: ["article_id"]; isOneToOne: false; referencedRelation: "articles"; referencedColumns: ["id"] },
          { foreignKeyName: "article_tags_tag_id_fkey"; columns: ["tag_id"]; isOneToOne: false; referencedRelation: "tags"; referencedColumns: ["id"] }
        ];
      };
      articles: {
        Row: {
          id: string;
          slug: string;
          title_en: string;
          title_ar: string;
          excerpt_en: string | null;
          excerpt_ar: string | null;
          body_en: string | null;
          body_ar: string | null;
          author_id: string | null;
          category_id: string | null;
          cover_path: string | null;
          cover_alt_en: string | null;
          cover_alt_ar: string | null;
          seo_title_en: string | null;
          seo_title_ar: string | null;
          seo_description_en: string | null;
          seo_description_ar: string | null;
          language_status: Database["public"]["Enums"]["language_status"];
          status: Database["public"]["Enums"]["content_status"];
          scheduled_for: string | null;
          published_at: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          reading_minutes: number | null;
        };
        Insert: {
          id?: string;
          slug: string;
          title_en?: string;
          title_ar?: string;
          excerpt_en?: string | null;
          excerpt_ar?: string | null;
          body_en?: string | null;
          body_ar?: string | null;
          author_id?: string | null;
          category_id?: string | null;
          cover_path?: string | null;
          cover_alt_en?: string | null;
          cover_alt_ar?: string | null;
          seo_title_en?: string | null;
          seo_title_ar?: string | null;
          seo_description_en?: string | null;
          seo_description_ar?: string | null;
          language_status?: Database["public"]["Enums"]["language_status"];
          status?: Database["public"]["Enums"]["content_status"];
          scheduled_for?: string | null;
          published_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          reading_minutes?: number | null;
        };
        Update: {
          id?: string;
          slug?: string;
          title_en?: string;
          title_ar?: string;
          excerpt_en?: string | null;
          excerpt_ar?: string | null;
          body_en?: string | null;
          body_ar?: string | null;
          author_id?: string | null;
          category_id?: string | null;
          cover_path?: string | null;
          cover_alt_en?: string | null;
          cover_alt_ar?: string | null;
          seo_title_en?: string | null;
          seo_title_ar?: string | null;
          seo_description_en?: string | null;
          seo_description_ar?: string | null;
          language_status?: Database["public"]["Enums"]["language_status"];
          status?: Database["public"]["Enums"]["content_status"];
          scheduled_for?: string | null;
          published_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          reading_minutes?: number | null;
        };
        Relationships: [
          { foreignKeyName: "articles_author_fk"; columns: ["author_id"]; isOneToOne: false; referencedRelation: "authors"; referencedColumns: ["id"] },
          { foreignKeyName: "articles_category_fk"; columns: ["category_id"]; isOneToOne: false; referencedRelation: "categories"; referencedColumns: ["id"] }
        ];
      };
      audit_logs: {
        Row: {
          id: number;
          actor_id: string | null;
          actor_email: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          client_id: string | null;
          metadata: Json;
          ip: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          actor_id?: string | null;
          actor_email?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          client_id?: string | null;
          metadata?: Json;
          ip?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          actor_id?: string | null;
          actor_email?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          client_id?: string | null;
          metadata?: Json;
          ip?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      authors: {
        Row: {
          id: string;
          user_id: string | null;
          name_en: string;
          name_ar: string;
          title_en: string | null;
          title_ar: string | null;
          bio_en: string | null;
          bio_ar: string | null;
          avatar_path: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          name_en: string;
          name_ar: string;
          title_en?: string | null;
          title_ar?: string | null;
          bio_en?: string | null;
          bio_ar?: string | null;
          avatar_path?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          name_en?: string;
          name_ar?: string;
          title_en?: string | null;
          title_ar?: string | null;
          bio_en?: string | null;
          bio_ar?: string | null;
          avatar_path?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "authors_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      case_studies: {
        Row: {
          id: string;
          slug: string;
          title_en: string;
          title_ar: string;
          summary_en: string | null;
          summary_ar: string | null;
          challenge_en: string | null;
          challenge_ar: string | null;
          solution_en: string | null;
          solution_ar: string | null;
          implementation_en: string | null;
          implementation_ar: string | null;
          outcome_en: string | null;
          outcome_ar: string | null;
          impact: Json;
          practice: Database["public"]["Enums"]["practice"];
          client_display_name_en: string | null;
          client_display_name_ar: string | null;
          industry_en: string | null;
          industry_ar: string | null;
          year: number | null;
          cover_path: string | null;
          cover_alt_en: string | null;
          cover_alt_ar: string | null;
          seo_title_en: string | null;
          seo_title_ar: string | null;
          seo_description_en: string | null;
          seo_description_ar: string | null;
          language_status: Database["public"]["Enums"]["language_status"];
          status: Database["public"]["Enums"]["content_status"];
          published_at: string | null;
          position: number;
          internal_project_id: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title_en?: string;
          title_ar?: string;
          summary_en?: string | null;
          summary_ar?: string | null;
          challenge_en?: string | null;
          challenge_ar?: string | null;
          solution_en?: string | null;
          solution_ar?: string | null;
          implementation_en?: string | null;
          implementation_ar?: string | null;
          outcome_en?: string | null;
          outcome_ar?: string | null;
          impact?: Json;
          practice?: Database["public"]["Enums"]["practice"];
          client_display_name_en?: string | null;
          client_display_name_ar?: string | null;
          industry_en?: string | null;
          industry_ar?: string | null;
          year?: number | null;
          cover_path?: string | null;
          cover_alt_en?: string | null;
          cover_alt_ar?: string | null;
          seo_title_en?: string | null;
          seo_title_ar?: string | null;
          seo_description_en?: string | null;
          seo_description_ar?: string | null;
          language_status?: Database["public"]["Enums"]["language_status"];
          status?: Database["public"]["Enums"]["content_status"];
          published_at?: string | null;
          position?: number;
          internal_project_id?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title_en?: string;
          title_ar?: string;
          summary_en?: string | null;
          summary_ar?: string | null;
          challenge_en?: string | null;
          challenge_ar?: string | null;
          solution_en?: string | null;
          solution_ar?: string | null;
          implementation_en?: string | null;
          implementation_ar?: string | null;
          outcome_en?: string | null;
          outcome_ar?: string | null;
          impact?: Json;
          practice?: Database["public"]["Enums"]["practice"];
          client_display_name_en?: string | null;
          client_display_name_ar?: string | null;
          industry_en?: string | null;
          industry_ar?: string | null;
          year?: number | null;
          cover_path?: string | null;
          cover_alt_en?: string | null;
          cover_alt_ar?: string | null;
          seo_title_en?: string | null;
          seo_title_ar?: string | null;
          seo_description_en?: string | null;
          seo_description_ar?: string | null;
          language_status?: Database["public"]["Enums"]["language_status"];
          status?: Database["public"]["Enums"]["content_status"];
          published_at?: string | null;
          position?: number;
          internal_project_id?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "case_studies_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "case_studies_internal_project_id_fkey"; columns: ["internal_project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
          { foreignKeyName: "case_studies_updated_by_fkey"; columns: ["updated_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      categories: {
        Row: {
          id: string;
          kind: string;
          slug: string;
          name_en: string;
          name_ar: string;
          position: number;
        };
        Insert: {
          id?: string;
          kind: string;
          slug: string;
          name_en: string;
          name_ar: string;
          position?: number;
        };
        Update: {
          id?: string;
          kind?: string;
          slug?: string;
          name_en?: string;
          name_ar?: string;
          position?: number;
        };
        Relationships: [];
      };
      certificates: {
        Row: {
          id: string;
          certificate_no: string | null;
          verification_code: string;
          type: Database["public"]["Enums"]["certificate_type"];
          status: Database["public"]["Enums"]["certificate_status"];
          language: Database["public"]["Enums"]["locale"];
          recipient_name_en: string;
          recipient_name_ar: string | null;
          recipient_email: string | null;
          recipient_user_id: string | null;
          title_en: string;
          title_ar: string | null;
          description_en: string | null;
          description_ar: string | null;
          program_name_en: string | null;
          program_name_ar: string | null;
          role_title_en: string | null;
          role_title_ar: string | null;
          start_date: string | null;
          end_date: string | null;
          hours: number | null;
          issue_date: string | null;
          issued_at: string | null;
          issued_by: string | null;
          signatory_name_en: string | null;
          signatory_name_ar: string | null;
          signatory_title_en: string | null;
          signatory_title_ar: string | null;
          revoked_at: string | null;
          revoked_by: string | null;
          revoke_reason: string | null;
          pdf_path: string | null;
          metadata: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          certificate_no?: string | null;
          verification_code?: string;
          type?: Database["public"]["Enums"]["certificate_type"];
          status?: Database["public"]["Enums"]["certificate_status"];
          language?: Database["public"]["Enums"]["locale"];
          recipient_name_en: string;
          recipient_name_ar?: string | null;
          recipient_email?: string | null;
          recipient_user_id?: string | null;
          title_en: string;
          title_ar?: string | null;
          description_en?: string | null;
          description_ar?: string | null;
          program_name_en?: string | null;
          program_name_ar?: string | null;
          role_title_en?: string | null;
          role_title_ar?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          hours?: number | null;
          issue_date?: string | null;
          issued_at?: string | null;
          issued_by?: string | null;
          signatory_name_en?: string | null;
          signatory_name_ar?: string | null;
          signatory_title_en?: string | null;
          signatory_title_ar?: string | null;
          revoked_at?: string | null;
          revoked_by?: string | null;
          revoke_reason?: string | null;
          pdf_path?: string | null;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          certificate_no?: string | null;
          verification_code?: string;
          type?: Database["public"]["Enums"]["certificate_type"];
          status?: Database["public"]["Enums"]["certificate_status"];
          language?: Database["public"]["Enums"]["locale"];
          recipient_name_en?: string;
          recipient_name_ar?: string | null;
          recipient_email?: string | null;
          recipient_user_id?: string | null;
          title_en?: string;
          title_ar?: string | null;
          description_en?: string | null;
          description_ar?: string | null;
          program_name_en?: string | null;
          program_name_ar?: string | null;
          role_title_en?: string | null;
          role_title_ar?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          hours?: number | null;
          issue_date?: string | null;
          issued_at?: string | null;
          issued_by?: string | null;
          signatory_name_en?: string | null;
          signatory_name_ar?: string | null;
          signatory_title_en?: string | null;
          signatory_title_ar?: string | null;
          revoked_at?: string | null;
          revoked_by?: string | null;
          revoke_reason?: string | null;
          pdf_path?: string | null;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "certificates_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "certificates_issued_by_fkey"; columns: ["issued_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "certificates_recipient_user_id_fkey"; columns: ["recipient_user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "certificates_revoked_by_fkey"; columns: ["revoked_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      client_contacts: {
        Row: {
          id: string;
          client_id: string;
          name: string;
          email: string | null;
          phone: string | null;
          title: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          name: string;
          email?: string | null;
          phone?: string | null;
          title?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          name?: string;
          email?: string | null;
          phone?: string | null;
          title?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "client_contacts_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] }
        ];
      };
      client_users: {
        Row: {
          user_id: string;
          client_id: string;
          is_primary: boolean;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          user_id: string;
          client_id: string;
          is_primary?: boolean;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          client_id?: string;
          is_primary?: boolean;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "client_users_client_fk"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "client_users_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      clients: {
        Row: {
          id: string;
          name_en: string;
          name_ar: string | null;
          legal_name: string | null;
          country: string | null;
          city: string | null;
          address: string | null;
          tax_number: string | null;
          website: string | null;
          primary_contact_name: string | null;
          primary_contact_email: string | null;
          phone: string | null;
          status: string;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          reference: string | null;
        };
        Insert: {
          id?: string;
          name_en: string;
          name_ar?: string | null;
          legal_name?: string | null;
          country?: string | null;
          city?: string | null;
          address?: string | null;
          tax_number?: string | null;
          website?: string | null;
          primary_contact_name?: string | null;
          primary_contact_email?: string | null;
          phone?: string | null;
          status?: string;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          reference?: string | null;
        };
        Update: {
          id?: string;
          name_en?: string;
          name_ar?: string | null;
          legal_name?: string | null;
          country?: string | null;
          city?: string | null;
          address?: string | null;
          tax_number?: string | null;
          website?: string | null;
          primary_contact_name?: string | null;
          primary_contact_email?: string | null;
          phone?: string | null;
          status?: string;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          reference?: string | null;
        };
        Relationships: [
          { foreignKeyName: "clients_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      contact_submissions: {
        Row: {
          id: string;
          name: string;
          email: string;
          company: string | null;
          country: string | null;
          service: string | null;
          message: string;
          locale: Database["public"]["Enums"]["locale"];
          ip_hash: string | null;
          status: string;
          handled_by: string | null;
          created_at: string;
          reference: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          company?: string | null;
          country?: string | null;
          service?: string | null;
          message: string;
          locale?: Database["public"]["Enums"]["locale"];
          ip_hash?: string | null;
          status?: string;
          handled_by?: string | null;
          created_at?: string;
          reference?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          company?: string | null;
          country?: string | null;
          service?: string | null;
          message?: string;
          locale?: Database["public"]["Enums"]["locale"];
          ip_hash?: string | null;
          status?: string;
          handled_by?: string | null;
          created_at?: string;
          reference?: string | null;
        };
        Relationships: [
          { foreignKeyName: "contact_submissions_handled_by_fkey"; columns: ["handled_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      departments: {
        Row: {
          id: string;
          name_en: string;
          name_ar: string;
          position: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name_en: string;
          name_ar: string;
          position?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name_en?: string;
          name_ar?: string;
          position?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      employee_documents: {
        Row: {
          id: string;
          employee_user_id: string;
          kind: Database["public"]["Enums"]["document_kind"];
          title: string;
          storage_path: string;
          size_bytes: number | null;
          mime_type: string | null;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          employee_user_id: string;
          kind?: Database["public"]["Enums"]["document_kind"];
          title: string;
          storage_path: string;
          size_bytes?: number | null;
          mime_type?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          employee_user_id?: string;
          kind?: Database["public"]["Enums"]["document_kind"];
          title?: string;
          storage_path?: string;
          size_bytes?: number | null;
          mime_type?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "employee_documents_employee_user_id_fkey"; columns: ["employee_user_id"]; isOneToOne: false; referencedRelation: "employees"; referencedColumns: ["user_id"] },
          { foreignKeyName: "employee_documents_uploaded_by_fkey"; columns: ["uploaded_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      employees: {
        Row: {
          user_id: string;
          employee_no: string | null;
          department_id: string | null;
          job_title_en: string;
          job_title_ar: string | null;
          employment_status: Database["public"]["Enums"]["employment_status"];
          start_date: string | null;
          end_date: string | null;
          work_phone: string | null;
          work_email: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          employee_no?: string | null;
          department_id?: string | null;
          job_title_en?: string;
          job_title_ar?: string | null;
          employment_status?: Database["public"]["Enums"]["employment_status"];
          start_date?: string | null;
          end_date?: string | null;
          work_phone?: string | null;
          work_email?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          employee_no?: string | null;
          department_id?: string | null;
          job_title_en?: string;
          job_title_ar?: string | null;
          employment_status?: Database["public"]["Enums"]["employment_status"];
          start_date?: string | null;
          end_date?: string | null;
          work_phone?: string | null;
          work_email?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "employees_department_id_fkey"; columns: ["department_id"]; isOneToOne: false; referencedRelation: "departments"; referencedColumns: ["id"] },
          { foreignKeyName: "employees_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      engagement_assets: {
        Row: {
          id: string;
          engagement_id: string;
          name: string;
          type: Database["public"]["Enums"]["asset_type"];
          identifier: string | null;
          in_scope: boolean;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          engagement_id: string;
          name: string;
          type?: Database["public"]["Enums"]["asset_type"];
          identifier?: string | null;
          in_scope?: boolean;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          engagement_id?: string;
          name?: string;
          type?: Database["public"]["Enums"]["asset_type"];
          identifier?: string | null;
          in_scope?: boolean;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "engagement_assets_engagement_id_fkey"; columns: ["engagement_id"]; isOneToOne: false; referencedRelation: "security_engagements"; referencedColumns: ["id"] }
        ];
      };
      engagement_members: {
        Row: {
          engagement_id: string;
          user_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          engagement_id: string;
          user_id: string;
          role?: string;
          created_at?: string;
        };
        Update: {
          engagement_id?: string;
          user_id?: string;
          role?: string;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "engagement_members_engagement_id_fkey"; columns: ["engagement_id"]; isOneToOne: false; referencedRelation: "security_engagements"; referencedColumns: ["id"] },
          { foreignKeyName: "engagement_members_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      engagement_reports: {
        Row: {
          id: string;
          engagement_id: string;
          version: number;
          title: string;
          storage_path: string;
          status: Database["public"]["Enums"]["report_status"];
          client_visible: boolean;
          issued_at: string | null;
          issued_by: string | null;
          uploaded_by: string | null;
          created_at: string;
          reference: string | null;
        };
        Insert: {
          id?: string;
          engagement_id: string;
          version?: number;
          title: string;
          storage_path: string;
          status?: Database["public"]["Enums"]["report_status"];
          client_visible?: boolean;
          issued_at?: string | null;
          issued_by?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
          reference?: string | null;
        };
        Update: {
          id?: string;
          engagement_id?: string;
          version?: number;
          title?: string;
          storage_path?: string;
          status?: Database["public"]["Enums"]["report_status"];
          client_visible?: boolean;
          issued_at?: string | null;
          issued_by?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
          reference?: string | null;
        };
        Relationships: [
          { foreignKeyName: "engagement_reports_engagement_id_fkey"; columns: ["engagement_id"]; isOneToOne: false; referencedRelation: "security_engagements"; referencedColumns: ["id"] },
          { foreignKeyName: "engagement_reports_issued_by_fkey"; columns: ["issued_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "engagement_reports_uploaded_by_fkey"; columns: ["uploaded_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      finding_evidence: {
        Row: {
          id: string;
          finding_id: string;
          storage_path: string;
          caption: string | null;
          mime_type: string | null;
          size_bytes: number | null;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          finding_id: string;
          storage_path: string;
          caption?: string | null;
          mime_type?: string | null;
          size_bytes?: number | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          finding_id?: string;
          storage_path?: string;
          caption?: string | null;
          mime_type?: string | null;
          size_bytes?: number | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "finding_evidence_finding_id_fkey"; columns: ["finding_id"]; isOneToOne: false; referencedRelation: "findings"; referencedColumns: ["id"] },
          { foreignKeyName: "finding_evidence_uploaded_by_fkey"; columns: ["uploaded_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      findings: {
        Row: {
          id: string;
          engagement_id: string;
          asset_id: string | null;
          ref_code: string;
          title: string;
          severity: Database["public"]["Enums"]["finding_severity"];
          cvss_score: number | null;
          status: Database["public"]["Enums"]["finding_status"];
          description: string | null;
          impact: string | null;
          evidence_summary: string | null;
          recommendation: string | null;
          discovered_at: string | null;
          remediated_at: string | null;
          retested_at: string | null;
          retest_result: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          engagement_id: string;
          asset_id?: string | null;
          ref_code: string;
          title: string;
          severity?: Database["public"]["Enums"]["finding_severity"];
          cvss_score?: number | null;
          status?: Database["public"]["Enums"]["finding_status"];
          description?: string | null;
          impact?: string | null;
          evidence_summary?: string | null;
          recommendation?: string | null;
          discovered_at?: string | null;
          remediated_at?: string | null;
          retested_at?: string | null;
          retest_result?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          engagement_id?: string;
          asset_id?: string | null;
          ref_code?: string;
          title?: string;
          severity?: Database["public"]["Enums"]["finding_severity"];
          cvss_score?: number | null;
          status?: Database["public"]["Enums"]["finding_status"];
          description?: string | null;
          impact?: string | null;
          evidence_summary?: string | null;
          recommendation?: string | null;
          discovered_at?: string | null;
          remediated_at?: string | null;
          retested_at?: string | null;
          retest_result?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "findings_asset_id_fkey"; columns: ["asset_id"]; isOneToOne: false; referencedRelation: "engagement_assets"; referencedColumns: ["id"] },
          { foreignKeyName: "findings_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "findings_engagement_id_fkey"; columns: ["engagement_id"]; isOneToOne: false; referencedRelation: "security_engagements"; referencedColumns: ["id"] }
        ];
      };
      invoice_items: {
        Row: {
          id: string;
          invoice_id: string;
          position: number;
          description_en: string;
          description_ar: string | null;
          quantity: number;
          unit_price: number;
          amount: number | null;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          position?: number;
          description_en: string;
          description_ar?: string | null;
          quantity?: number;
          unit_price?: number;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          position?: number;
          description_en?: string;
          description_ar?: string | null;
          quantity?: number;
          unit_price?: number;
        };
        Relationships: [
          { foreignKeyName: "invoice_items_invoice_id_fkey"; columns: ["invoice_id"]; isOneToOne: false; referencedRelation: "invoices"; referencedColumns: ["id"] }
        ];
      };
      invoices: {
        Row: {
          id: string;
          number: string | null;
          client_id: string;
          project_id: string | null;
          quote_id: string | null;
          replaces_invoice_id: string | null;
          language: Database["public"]["Enums"]["locale"];
          currency: string;
          status: Database["public"]["Enums"]["invoice_status"];
          issue_date: string | null;
          due_date: string | null;
          subtotal: number;
          tax_rate: number;
          tax_amount: number;
          total: number;
          amount_paid: number;
          title_en: string | null;
          title_ar: string | null;
          notes_en: string | null;
          notes_ar: string | null;
          terms_en: string | null;
          terms_ar: string | null;
          pdf_path: string | null;
          void_reason: string | null;
          voided_at: string | null;
          created_by: string | null;
          issued_by: string | null;
          issued_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          number?: string | null;
          client_id: string;
          project_id?: string | null;
          quote_id?: string | null;
          replaces_invoice_id?: string | null;
          language?: Database["public"]["Enums"]["locale"];
          currency?: string;
          status?: Database["public"]["Enums"]["invoice_status"];
          issue_date?: string | null;
          due_date?: string | null;
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          total?: number;
          amount_paid?: number;
          title_en?: string | null;
          title_ar?: string | null;
          notes_en?: string | null;
          notes_ar?: string | null;
          terms_en?: string | null;
          terms_ar?: string | null;
          pdf_path?: string | null;
          void_reason?: string | null;
          voided_at?: string | null;
          created_by?: string | null;
          issued_by?: string | null;
          issued_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          number?: string | null;
          client_id?: string;
          project_id?: string | null;
          quote_id?: string | null;
          replaces_invoice_id?: string | null;
          language?: Database["public"]["Enums"]["locale"];
          currency?: string;
          status?: Database["public"]["Enums"]["invoice_status"];
          issue_date?: string | null;
          due_date?: string | null;
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          total?: number;
          amount_paid?: number;
          title_en?: string | null;
          title_ar?: string | null;
          notes_en?: string | null;
          notes_ar?: string | null;
          terms_en?: string | null;
          terms_ar?: string | null;
          pdf_path?: string | null;
          void_reason?: string | null;
          voided_at?: string | null;
          created_by?: string | null;
          issued_by?: string | null;
          issued_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "invoices_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "invoices_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "invoices_issued_by_fkey"; columns: ["issued_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "invoices_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
          { foreignKeyName: "invoices_quote_id_fkey"; columns: ["quote_id"]; isOneToOne: false; referencedRelation: "quotes"; referencedColumns: ["id"] },
          { foreignKeyName: "invoices_replaces_invoice_id_fkey"; columns: ["replaces_invoice_id"]; isOneToOne: false; referencedRelation: "invoices"; referencedColumns: ["id"] }
        ];
      };
      milestones: {
        Row: {
          id: string;
          project_id: string;
          title_en: string;
          title_ar: string | null;
          description: string | null;
          due_date: string | null;
          status: Database["public"]["Enums"]["milestone_status"];
          client_visible: boolean;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          title_en: string;
          title_ar?: string | null;
          description?: string | null;
          due_date?: string | null;
          status?: Database["public"]["Enums"]["milestone_status"];
          client_visible?: boolean;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          title_en?: string;
          title_ar?: string | null;
          description?: string | null;
          due_date?: string | null;
          status?: Database["public"]["Enums"]["milestone_status"];
          client_visible?: boolean;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "milestones_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] }
        ];
      };
      news_posts: {
        Row: {
          id: string;
          slug: string;
          title_en: string;
          title_ar: string;
          excerpt_en: string | null;
          excerpt_ar: string | null;
          body_en: string | null;
          body_ar: string | null;
          author_id: string | null;
          category_id: string | null;
          cover_path: string | null;
          cover_alt_en: string | null;
          cover_alt_ar: string | null;
          seo_title_en: string | null;
          seo_title_ar: string | null;
          seo_description_en: string | null;
          seo_description_ar: string | null;
          language_status: Database["public"]["Enums"]["language_status"];
          status: Database["public"]["Enums"]["content_status"];
          scheduled_for: string | null;
          published_at: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title_en?: string;
          title_ar?: string;
          excerpt_en?: string | null;
          excerpt_ar?: string | null;
          body_en?: string | null;
          body_ar?: string | null;
          author_id?: string | null;
          category_id?: string | null;
          cover_path?: string | null;
          cover_alt_en?: string | null;
          cover_alt_ar?: string | null;
          seo_title_en?: string | null;
          seo_title_ar?: string | null;
          seo_description_en?: string | null;
          seo_description_ar?: string | null;
          language_status?: Database["public"]["Enums"]["language_status"];
          status?: Database["public"]["Enums"]["content_status"];
          scheduled_for?: string | null;
          published_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title_en?: string;
          title_ar?: string;
          excerpt_en?: string | null;
          excerpt_ar?: string | null;
          body_en?: string | null;
          body_ar?: string | null;
          author_id?: string | null;
          category_id?: string | null;
          cover_path?: string | null;
          cover_alt_en?: string | null;
          cover_alt_ar?: string | null;
          seo_title_en?: string | null;
          seo_title_ar?: string | null;
          seo_description_en?: string | null;
          seo_description_ar?: string | null;
          language_status?: Database["public"]["Enums"]["language_status"];
          status?: Database["public"]["Enums"]["content_status"];
          scheduled_for?: string | null;
          published_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "news_posts_author_id_fkey"; columns: ["author_id"]; isOneToOne: false; referencedRelation: "authors"; referencedColumns: ["id"] },
          { foreignKeyName: "news_posts_category_id_fkey"; columns: ["category_id"]; isOneToOne: false; referencedRelation: "categories"; referencedColumns: ["id"] },
          { foreignKeyName: "news_posts_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "news_posts_updated_by_fkey"; columns: ["updated_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      news_tags: {
        Row: {
          news_id: string;
          tag_id: string;
        };
        Insert: {
          news_id: string;
          tag_id: string;
        };
        Update: {
          news_id?: string;
          tag_id?: string;
        };
        Relationships: [
          { foreignKeyName: "news_tags_news_id_fkey"; columns: ["news_id"]; isOneToOne: false; referencedRelation: "news_posts"; referencedColumns: ["id"] },
          { foreignKeyName: "news_tags_tag_id_fkey"; columns: ["tag_id"]; isOneToOne: false; referencedRelation: "tags"; referencedColumns: ["id"] }
        ];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title_en: string;
          title_ar: string;
          body_en: string | null;
          body_ar: string | null;
          link: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title_en: string;
          title_ar: string;
          body_en?: string | null;
          body_ar?: string | null;
          link?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title_en?: string;
          title_ar?: string;
          body_en?: string | null;
          body_ar?: string | null;
          link?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "notifications_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      payments: {
        Row: {
          id: string;
          invoice_id: string;
          amount: number;
          paid_at: string;
          method: string;
          reference: string | null;
          notes: string | null;
          recorded_by: string | null;
          created_at: string;
          receipt_no: string | null;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          amount: number;
          paid_at?: string;
          method?: string;
          reference?: string | null;
          notes?: string | null;
          recorded_by?: string | null;
          created_at?: string;
          receipt_no?: string | null;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          amount?: number;
          paid_at?: string;
          method?: string;
          reference?: string | null;
          notes?: string | null;
          recorded_by?: string | null;
          created_at?: string;
          receipt_no?: string | null;
        };
        Relationships: [
          { foreignKeyName: "payments_invoice_id_fkey"; columns: ["invoice_id"]; isOneToOne: false; referencedRelation: "invoices"; referencedColumns: ["id"] },
          { foreignKeyName: "payments_recorded_by_fkey"; columns: ["recorded_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      permissions: {
        Row: {
          key: string;
          description: string;
        };
        Insert: {
          key: string;
          description: string;
        };
        Update: {
          key?: string;
          description?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          full_name_ar: string | null;
          kind: Database["public"]["Enums"]["user_kind"];
          locale: Database["public"]["Enums"]["locale"];
          avatar_path: string | null;
          phone: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string;
          full_name_ar?: string | null;
          kind?: Database["public"]["Enums"]["user_kind"];
          locale?: Database["public"]["Enums"]["locale"];
          avatar_path?: string | null;
          phone?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          full_name_ar?: string | null;
          kind?: Database["public"]["Enums"]["user_kind"];
          locale?: Database["public"]["Enums"]["locale"];
          avatar_path?: string | null;
          phone?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      project_documents: {
        Row: {
          id: string;
          project_id: string;
          title: string;
          category: string;
          storage_path: string;
          size_bytes: number | null;
          mime_type: string | null;
          client_visible: boolean;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          title: string;
          category?: string;
          storage_path: string;
          size_bytes?: number | null;
          mime_type?: string | null;
          client_visible?: boolean;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          title?: string;
          category?: string;
          storage_path?: string;
          size_bytes?: number | null;
          mime_type?: string | null;
          client_visible?: boolean;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "project_documents_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
          { foreignKeyName: "project_documents_uploaded_by_fkey"; columns: ["uploaded_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      project_members: {
        Row: {
          project_id: string;
          user_id: string;
          role: Database["public"]["Enums"]["project_member_role"];
          added_by: string | null;
          created_at: string;
        };
        Insert: {
          project_id: string;
          user_id: string;
          role?: Database["public"]["Enums"]["project_member_role"];
          added_by?: string | null;
          created_at?: string;
        };
        Update: {
          project_id?: string;
          user_id?: string;
          role?: Database["public"]["Enums"]["project_member_role"];
          added_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "project_members_added_by_fkey"; columns: ["added_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "project_members_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
          { foreignKeyName: "project_members_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      project_updates: {
        Row: {
          id: string;
          project_id: string;
          title: string;
          body: string;
          client_visible: boolean;
          author_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          title: string;
          body: string;
          client_visible?: boolean;
          author_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          title?: string;
          body?: string;
          client_visible?: boolean;
          author_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "project_updates_author_id_fkey"; columns: ["author_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "project_updates_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] }
        ];
      };
      projects: {
        Row: {
          id: string;
          code: string;
          client_id: string | null;
          name_en: string;
          name_ar: string | null;
          practice: Database["public"]["Enums"]["practice"];
          status: Database["public"]["Enums"]["project_status"];
          description: string | null;
          manager_user_id: string | null;
          start_date: string | null;
          end_date: string | null;
          client_visible: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          client_id?: string | null;
          name_en: string;
          name_ar?: string | null;
          practice?: Database["public"]["Enums"]["practice"];
          status?: Database["public"]["Enums"]["project_status"];
          description?: string | null;
          manager_user_id?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          client_visible?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          client_id?: string | null;
          name_en?: string;
          name_ar?: string | null;
          practice?: Database["public"]["Enums"]["practice"];
          status?: Database["public"]["Enums"]["project_status"];
          description?: string | null;
          manager_user_id?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          client_visible?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "projects_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "projects_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "projects_manager_user_id_fkey"; columns: ["manager_user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      public_projects: {
        Row: {
          id: string;
          slug: string;
          title_en: string;
          title_ar: string;
          summary_en: string | null;
          summary_ar: string | null;
          body_en: string | null;
          body_ar: string | null;
          practice: Database["public"]["Enums"]["practice"];
          client_display_name_en: string | null;
          client_display_name_ar: string | null;
          year: number | null;
          services_en: string[];
          services_ar: string[];
          cover_path: string | null;
          cover_alt_en: string | null;
          cover_alt_ar: string | null;
          seo_title_en: string | null;
          seo_title_ar: string | null;
          seo_description_en: string | null;
          seo_description_ar: string | null;
          language_status: Database["public"]["Enums"]["language_status"];
          status: Database["public"]["Enums"]["content_status"];
          published_at: string | null;
          position: number;
          internal_project_id: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title_en?: string;
          title_ar?: string;
          summary_en?: string | null;
          summary_ar?: string | null;
          body_en?: string | null;
          body_ar?: string | null;
          practice?: Database["public"]["Enums"]["practice"];
          client_display_name_en?: string | null;
          client_display_name_ar?: string | null;
          year?: number | null;
          services_en?: string[];
          services_ar?: string[];
          cover_path?: string | null;
          cover_alt_en?: string | null;
          cover_alt_ar?: string | null;
          seo_title_en?: string | null;
          seo_title_ar?: string | null;
          seo_description_en?: string | null;
          seo_description_ar?: string | null;
          language_status?: Database["public"]["Enums"]["language_status"];
          status?: Database["public"]["Enums"]["content_status"];
          published_at?: string | null;
          position?: number;
          internal_project_id?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title_en?: string;
          title_ar?: string;
          summary_en?: string | null;
          summary_ar?: string | null;
          body_en?: string | null;
          body_ar?: string | null;
          practice?: Database["public"]["Enums"]["practice"];
          client_display_name_en?: string | null;
          client_display_name_ar?: string | null;
          year?: number | null;
          services_en?: string[];
          services_ar?: string[];
          cover_path?: string | null;
          cover_alt_en?: string | null;
          cover_alt_ar?: string | null;
          seo_title_en?: string | null;
          seo_title_ar?: string | null;
          seo_description_en?: string | null;
          seo_description_ar?: string | null;
          language_status?: Database["public"]["Enums"]["language_status"];
          status?: Database["public"]["Enums"]["content_status"];
          published_at?: string | null;
          position?: number;
          internal_project_id?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "public_projects_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "public_projects_internal_project_id_fkey"; columns: ["internal_project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] },
          { foreignKeyName: "public_projects_updated_by_fkey"; columns: ["updated_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      quote_items: {
        Row: {
          id: string;
          quote_id: string;
          position: number;
          description_en: string;
          description_ar: string | null;
          quantity: number;
          unit_price: number;
          amount: number | null;
        };
        Insert: {
          id?: string;
          quote_id: string;
          position?: number;
          description_en: string;
          description_ar?: string | null;
          quantity?: number;
          unit_price?: number;
        };
        Update: {
          id?: string;
          quote_id?: string;
          position?: number;
          description_en?: string;
          description_ar?: string | null;
          quantity?: number;
          unit_price?: number;
        };
        Relationships: [
          { foreignKeyName: "quote_items_quote_id_fkey"; columns: ["quote_id"]; isOneToOne: false; referencedRelation: "quotes"; referencedColumns: ["id"] }
        ];
      };
      quotes: {
        Row: {
          id: string;
          number: string | null;
          client_id: string;
          project_id: string | null;
          language: Database["public"]["Enums"]["locale"];
          currency: string;
          status: Database["public"]["Enums"]["quote_status"];
          issue_date: string | null;
          valid_until: string | null;
          subtotal: number;
          tax_rate: number;
          tax_amount: number;
          total: number;
          title_en: string | null;
          title_ar: string | null;
          notes_en: string | null;
          notes_ar: string | null;
          terms_en: string | null;
          terms_ar: string | null;
          pdf_path: string | null;
          created_by: string | null;
          issued_by: string | null;
          issued_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          number?: string | null;
          client_id: string;
          project_id?: string | null;
          language?: Database["public"]["Enums"]["locale"];
          currency?: string;
          status?: Database["public"]["Enums"]["quote_status"];
          issue_date?: string | null;
          valid_until?: string | null;
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          total?: number;
          title_en?: string | null;
          title_ar?: string | null;
          notes_en?: string | null;
          notes_ar?: string | null;
          terms_en?: string | null;
          terms_ar?: string | null;
          pdf_path?: string | null;
          created_by?: string | null;
          issued_by?: string | null;
          issued_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          number?: string | null;
          client_id?: string;
          project_id?: string | null;
          language?: Database["public"]["Enums"]["locale"];
          currency?: string;
          status?: Database["public"]["Enums"]["quote_status"];
          issue_date?: string | null;
          valid_until?: string | null;
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          total?: number;
          title_en?: string | null;
          title_ar?: string | null;
          notes_en?: string | null;
          notes_ar?: string | null;
          terms_en?: string | null;
          terms_ar?: string | null;
          pdf_path?: string | null;
          created_by?: string | null;
          issued_by?: string | null;
          issued_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "quotes_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "quotes_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "quotes_issued_by_fkey"; columns: ["issued_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "quotes_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] }
        ];
      };
      reference_sequences: {
        Row: {
          kind: string;
          next_value: number;
          updated_at: string;
        };
        Insert: {
          kind: string;
          next_value?: number;
          updated_at?: string;
        };
        Update: {
          kind?: string;
          next_value?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      role_permissions: {
        Row: {
          role_key: string;
          permission_key: string;
        };
        Insert: {
          role_key: string;
          permission_key: string;
        };
        Update: {
          role_key?: string;
          permission_key?: string;
        };
        Relationships: [
          { foreignKeyName: "role_permissions_permission_key_fkey"; columns: ["permission_key"]; isOneToOne: false; referencedRelation: "permissions"; referencedColumns: ["key"] },
          { foreignKeyName: "role_permissions_role_key_fkey"; columns: ["role_key"]; isOneToOne: false; referencedRelation: "roles"; referencedColumns: ["key"] }
        ];
      };
      roles: {
        Row: {
          key: string;
          name_en: string;
          name_ar: string;
          description: string | null;
          is_system: boolean;
          created_at: string;
        };
        Insert: {
          key: string;
          name_en: string;
          name_ar: string;
          description?: string | null;
          is_system?: boolean;
          created_at?: string;
        };
        Update: {
          key?: string;
          name_en?: string;
          name_ar?: string;
          description?: string | null;
          is_system?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      security_engagements: {
        Row: {
          id: string;
          code: string;
          client_id: string | null;
          project_id: string | null;
          title: string;
          type: Database["public"]["Enums"]["engagement_type"];
          status: Database["public"]["Enums"]["engagement_status"];
          scope_summary: string | null;
          rules_of_engagement: string | null;
          authorised_by_name: string | null;
          authorised_at: string | null;
          authorisation_document_path: string | null;
          start_date: string | null;
          end_date: string | null;
          lead_user_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          client_id?: string | null;
          project_id?: string | null;
          title: string;
          type?: Database["public"]["Enums"]["engagement_type"];
          status?: Database["public"]["Enums"]["engagement_status"];
          scope_summary?: string | null;
          rules_of_engagement?: string | null;
          authorised_by_name?: string | null;
          authorised_at?: string | null;
          authorisation_document_path?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          lead_user_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          client_id?: string | null;
          project_id?: string | null;
          title?: string;
          type?: Database["public"]["Enums"]["engagement_type"];
          status?: Database["public"]["Enums"]["engagement_status"];
          scope_summary?: string | null;
          rules_of_engagement?: string | null;
          authorised_by_name?: string | null;
          authorised_at?: string | null;
          authorisation_document_path?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          lead_user_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "security_engagements_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "security_engagements_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "security_engagements_lead_user_id_fkey"; columns: ["lead_user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "security_engagements_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] }
        ];
      };
      support_requests: {
        Row: {
          id: string;
          client_id: string;
          project_id: string | null;
          subject: string;
          body: string;
          status: Database["public"]["Enums"]["support_status"];
          created_by: string | null;
          assigned_to: string | null;
          created_at: string;
          updated_at: string;
          reference: string | null;
        };
        Insert: {
          id?: string;
          client_id: string;
          project_id?: string | null;
          subject: string;
          body: string;
          status?: Database["public"]["Enums"]["support_status"];
          created_by?: string | null;
          assigned_to?: string | null;
          created_at?: string;
          updated_at?: string;
          reference?: string | null;
        };
        Update: {
          id?: string;
          client_id?: string;
          project_id?: string | null;
          subject?: string;
          body?: string;
          status?: Database["public"]["Enums"]["support_status"];
          created_by?: string | null;
          assigned_to?: string | null;
          created_at?: string;
          updated_at?: string;
          reference?: string | null;
        };
        Relationships: [
          { foreignKeyName: "support_requests_assigned_to_fkey"; columns: ["assigned_to"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "support_requests_client_id_fkey"; columns: ["client_id"]; isOneToOne: false; referencedRelation: "clients"; referencedColumns: ["id"] },
          { foreignKeyName: "support_requests_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "support_requests_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] }
        ];
      };
      tags: {
        Row: {
          id: string;
          slug: string;
          name_en: string;
          name_ar: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name_en: string;
          name_ar: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name_en?: string;
          name_ar?: string;
        };
        Relationships: [];
      };
      task_comments: {
        Row: {
          id: string;
          task_id: string;
          author_id: string | null;
          body: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          task_id: string;
          author_id?: string | null;
          body: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          task_id?: string;
          author_id?: string | null;
          body?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "task_comments_author_id_fkey"; columns: ["author_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "task_comments_task_id_fkey"; columns: ["task_id"]; isOneToOne: false; referencedRelation: "tasks"; referencedColumns: ["id"] }
        ];
      };
      tasks: {
        Row: {
          id: string;
          project_id: string;
          milestone_id: string | null;
          title: string;
          description: string | null;
          status: Database["public"]["Enums"]["task_status"];
          priority: Database["public"]["Enums"]["task_priority"];
          assignee_user_id: string | null;
          due_date: string | null;
          position: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          reference: string | null;
        };
        Insert: {
          id?: string;
          project_id: string;
          milestone_id?: string | null;
          title: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["task_status"];
          priority?: Database["public"]["Enums"]["task_priority"];
          assignee_user_id?: string | null;
          due_date?: string | null;
          position?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          reference?: string | null;
        };
        Update: {
          id?: string;
          project_id?: string;
          milestone_id?: string | null;
          title?: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["task_status"];
          priority?: Database["public"]["Enums"]["task_priority"];
          assignee_user_id?: string | null;
          due_date?: string | null;
          position?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          reference?: string | null;
        };
        Relationships: [
          { foreignKeyName: "tasks_assignee_user_id_fkey"; columns: ["assignee_user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "tasks_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "tasks_milestone_id_fkey"; columns: ["milestone_id"]; isOneToOne: false; referencedRelation: "milestones"; referencedColumns: ["id"] },
          { foreignKeyName: "tasks_project_id_fkey"; columns: ["project_id"]; isOneToOne: false; referencedRelation: "projects"; referencedColumns: ["id"] }
        ];
      };
      team_members: {
        Row: {
          team_id: string;
          user_id: string;
        };
        Insert: {
          team_id: string;
          user_id: string;
        };
        Update: {
          team_id?: string;
          user_id?: string;
        };
        Relationships: [
          { foreignKeyName: "team_members_team_id_fkey"; columns: ["team_id"]; isOneToOne: false; referencedRelation: "teams"; referencedColumns: ["id"] },
          { foreignKeyName: "team_members_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      teams: {
        Row: {
          id: string;
          department_id: string | null;
          name_en: string;
          name_ar: string;
          lead_user_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          department_id?: string | null;
          name_en: string;
          name_ar: string;
          lead_user_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          department_id?: string | null;
          name_en?: string;
          name_ar?: string;
          lead_user_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "teams_department_id_fkey"; columns: ["department_id"]; isOneToOne: false; referencedRelation: "departments"; referencedColumns: ["id"] },
          { foreignKeyName: "teams_lead_user_id_fkey"; columns: ["lead_user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
      user_roles: {
        Row: {
          user_id: string;
          role_key: string;
          granted_by: string | null;
          granted_at: string;
        };
        Insert: {
          user_id: string;
          role_key: string;
          granted_by?: string | null;
          granted_at?: string;
        };
        Update: {
          user_id?: string;
          role_key?: string;
          granted_by?: string | null;
          granted_at?: string;
        };
        Relationships: [
          { foreignKeyName: "user_roles_granted_by_fkey"; columns: ["granted_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "user_roles_role_key_fkey"; columns: ["role_key"]; isOneToOne: false; referencedRelation: "roles"; referencedColumns: ["key"] },
          { foreignKeyName: "user_roles_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }
        ];
      };
    };
    Views: {
      employee_directory: {
        Row: {
          user_id: string | null;
          full_name: string | null;
          full_name_ar: string | null;
          email: string | null;
          avatar_path: string | null;
          job_title_en: string | null;
          job_title_ar: string | null;
          department_id: string | null;
          department_name_en: string | null;
          department_name_ar: string | null;
          employment_status: Database["public"]["Enums"]["employment_status"] | null;
          work_phone: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      consume_rate_limit: {
        Args: {
          _key: string;
          _limit: number;
          _window_seconds: number;
        };
        Returns: boolean;
      };
      convert_quote_to_invoice: {
        Args: {
          _quote_id: string;
        };
        Returns: Database["public"]["Tables"]["invoices"]["Row"];
      };
      create_engagement: {
        Args: {
          _code: string;
          _title: string;
          _type: Database["public"]["Enums"]["engagement_type"];
          _client_id?: string;
          _project_id?: string;
          _lead_user_id?: string;
          _start_date?: string;
          _end_date?: string;
          _scope_summary?: string;
          _rules_of_engagement?: string;
          _authorised_by_name?: string;
          _authorised_at?: string;
        };
        Returns: Database["public"]["Tables"]["security_engagements"]["Row"];
      };
      create_replacement_invoice: {
        Args: {
          _invoice_id: string;
        };
        Returns: Database["public"]["Tables"]["invoices"]["Row"];
      };
      duplicate_quote: {
        Args: {
          _quote_id: string;
        };
        Returns: Database["public"]["Tables"]["quotes"]["Row"];
      };
      issue_certificate: {
        Args: {
          _certificate_id: string;
          _expected_updated_at: string;
          _issue_date?: string;
        };
        Returns: Database["public"]["Tables"]["certificates"]["Row"];
      };
      issue_invoice: {
        Args: {
          _invoice_id: string;
          _expected_updated_at: string;
          _issue_date?: string;
          _due_date?: string;
        };
        Returns: Database["public"]["Tables"]["invoices"]["Row"];
      };
      issue_quote: {
        Args: {
          _quote_id: string;
          _expected_updated_at: string;
          _issue_date?: string;
          _valid_until?: string;
        };
        Returns: Database["public"]["Tables"]["quotes"]["Row"];
      };
      mark_invoice_sent: {
        Args: {
          _invoice_id: string;
        };
        Returns: Database["public"]["Tables"]["invoices"]["Row"];
      };
      my_permissions: {
        Args: Record<PropertyKey, never>;
        Returns: string[];
      };
      publish_due_content: {
        Args: Record<PropertyKey, never>;
        Returns: number;
      };
      record_audit_event: {
        Args: {
          _action: string;
          _entity_type: string;
          _entity_id: string;
          _metadata?: Json;
          _client_id?: string;
          _ip?: string;
          _user_agent?: string;
          _actor_id?: string;
        };
        Returns: undefined;
      };
      record_payment: {
        Args: {
          _invoice_id: string;
          _amount: number;
          _paid_at: string;
          _method: string;
          _reference?: string;
          _notes?: string;
        };
        Returns: Database["public"]["Tables"]["payments"]["Row"];
      };
      remove_payment: {
        Args: {
          _payment_id: string;
          _reason: string;
        };
        Returns: Database["public"]["Tables"]["invoices"]["Row"];
      };
      revoke_certificate: {
        Args: {
          _certificate_id: string;
          _reason: string;
        };
        Returns: Database["public"]["Tables"]["certificates"]["Row"];
      };
      run_scheduled_jobs: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      save_invoice: {
        Args: {
          _header: Json;
          _items: Json;
          _id?: string;
          _expected_updated_at?: string;
        };
        Returns: Database["public"]["Tables"]["invoices"]["Row"];
      };
      save_quote: {
        Args: {
          _header: Json;
          _items: Json;
          _id?: string;
          _expected_updated_at?: string;
        };
        Returns: Database["public"]["Tables"]["quotes"]["Row"];
      };
      set_quote_status: {
        Args: {
          _quote_id: string;
          _status: Database["public"]["Enums"]["quote_status"];
        };
        Returns: Database["public"]["Tables"]["quotes"]["Row"];
      };
      verify_certificate: {
        Args: {
          _code: string;
        };
        Returns: { certificate_no: string | null; type: Database["public"]["Enums"]["certificate_type"] | null; status: Database["public"]["Enums"]["certificate_status"] | null; language: Database["public"]["Enums"]["locale"] | null; recipient_name_en: string | null; recipient_name_ar: string | null; title_en: string | null; title_ar: string | null; program_name_en: string | null; program_name_ar: string | null; role_title_en: string | null; role_title_ar: string | null; hours: number | null; start_date: string | null; end_date: string | null; issue_date: string | null; revoked_at: string | null }[];
      };
      viewer_context: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      void_invoice: {
        Args: {
          _invoice_id: string;
          _reason: string;
        };
        Returns: Database["public"]["Tables"]["invoices"]["Row"];
      };
    };
    Enums: {
      asset_type: "web_app" | "api" | "host" | "network" | "cloud" | "mobile_app" | "identity" | "other";
      certificate_status: "draft" | "issued" | "revoked";
      certificate_type: "training" | "internship" | "experience" | "appreciation" | "other";
      content_status: "draft" | "review" | "scheduled" | "published" | "archived";
      document_kind: "contract" | "id" | "certificate" | "experience_certificate" | "training_certificate" | "other";
      employment_status: "active" | "inactive" | "on_leave" | "ended";
      engagement_status: "scoping" | "authorised" | "active" | "reporting" | "remediation" | "retest" | "closed" | "cancelled";
      engagement_type: "penetration_test" | "compromise_assessment" | "dfir" | "security_assessment" | "red_team" | "consulting" | "training";
      finding_severity: "informational" | "low" | "medium" | "high" | "critical";
      finding_status: "open" | "in_remediation" | "remediated" | "retest_pending" | "verified" | "accepted_risk" | "false_positive";
      invoice_status: "draft" | "issued" | "sent" | "partially_paid" | "paid" | "overdue" | "void";
      language_status: "en_only" | "ar_only" | "both";
      locale: "en" | "ar";
      milestone_status: "planned" | "in_progress" | "completed";
      practice: "cybersecurity" | "development" | "ai" | "infrastructure" | "mixed";
      project_member_role: "manager" | "member" | "viewer";
      project_status: "draft" | "planned" | "active" | "on_hold" | "completed" | "cancelled";
      quote_status: "draft" | "sent" | "accepted" | "declined" | "expired" | "void";
      report_status: "draft" | "final";
      support_status: "open" | "in_progress" | "waiting_client" | "resolved" | "closed";
      task_priority: "low" | "medium" | "high" | "urgent";
      task_status: "todo" | "in_progress" | "review" | "done" | "cancelled";
      user_kind: "employee" | "client";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type Views<T extends keyof PublicSchema["Views"]> = PublicSchema["Views"][T]["Row"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];
export type Functions<T extends keyof PublicSchema["Functions"]> = PublicSchema["Functions"][T];
