"use client";

import * as React from "react";
import Image from "next/image";
import { Stream } from "@/components/brand/stream";
import type { StreamParams } from "@/components/brand/stream-math";

type Dir = "ltr" | "rtl";

/** Matches the `lg` breakpoint, where the copy moves beside the band instead of under it. */
const DESKTOP = "(min-width: 64rem)";

/**
 * Hero field parameters. The band reads in the writing direction: it starts
 * as one line on the start side (under the copy) and opens toward the end
 * side, so the right to left version mirrors the opening and the fade. On
 * phones the band rides higher so it stays clear of the copy at the bottom.
 * These are module constants: the canvas restarts whenever it receives a new
 * `params` object.
 */
const DESKTOP_LTR: StreamParams = { flow: 1.15 };
const DESKTOP_RTL: StreamParams = { flow: 1.15, opening: [0.2, 0.03], fadeIn: 100, fadeRight: true, fadeOut: 1.4 };
const PHONE_LTR: StreamParams = { flow: 1.15, cy0: 0.34, amp: 0.12, opening: [0.05, 0.17] };
const PHONE_RTL: StreamParams = { flow: 1.15, cy0: 0.34, amp: 0.12, opening: [0.17, 0.05], fadeIn: 100, fadeRight: true, fadeOut: 1.4 };

/** First paint files, generated by scripts/generate-stream-svgs.ts from the same maths. */
const HERO_STATIC: Record<Dir, string> = {
  ltr: "/brand/pattern/stream-opening-hero.svg",
  rtl: "/brand/pattern/stream-opening-hero-rtl.svg",
};

function subscribe(onChange: () => void) {
  const query = window.matchMedia(DESKTOP);
  query.addEventListener("change", onChange);
  return () => query.removeEventListener("change", onChange);
}
const getSnapshot = () => window.matchMedia(DESKTOP).matches;
const getServerSnapshot = () => true;

/**
 * The live Stream behind the home hero: the "opening" preset, always moving,
 * reacting to mouse and touch, with the static file as its first paint.
 */
export function HeroStream({ dir }: { dir: Dir }) {
  const desktop = React.useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot);
  const params = dir === "rtl" ? (desktop ? DESKTOP_RTL : PHONE_RTL) : desktop ? DESKTOP_LTR : PHONE_LTR;
  return (
    <Stream preset="opening" params={params} interactive className="absolute inset-0">
      <Image src={HERO_STATIC[dir]} alt="" fill priority unoptimized sizes="100vw" className="object-cover" />
    </Stream>
  );
}
