#!/usr/bin/env python3
"""Generates src/lib/supabase/database.types.ts from a database that has the
migrations applied (default: the local test database created by
supabase/tests/run.sh). Produces the same shape as `supabase gen types` so the
typed supabase-js client works without the Supabase CLI.

Usage: python3 scripts/generate-db-types.py > src/lib/supabase/database.types.ts
"""
import os, subprocess, json, sys

DB = os.environ.get("TEST_DB", "cybarq_test")
ENV = dict(os.environ, PGPASSWORD=os.environ.get("PGPASSWORD", "postgres"))

def q(sql):
    out = subprocess.run(["psql", "-h", os.environ.get("PGHOST", "localhost"), "-U", os.environ.get("PGUSER", "postgres"),
                          "-d", DB, "-X", "-A", "-t", "-c", sql], capture_output=True, text=True, env=ENV)
    if out.returncode != 0:
        sys.stderr.write(out.stderr); sys.exit(1)
    return out.stdout.strip()

enums = {}
for line in q("""select t.typname, string_agg(e.enumlabel, '|' order by e.enumsortorder)
  from pg_type t join pg_enum e on e.enumtypid = t.oid join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public' group by t.typname order by 1""").splitlines():
    name, labels = line.split("|", 1)
    enums[name] = labels.split("|")

def ts_type(udt, data_type, elem=None):
    base = udt.lstrip("_")
    if data_type == "ARRAY":
        return ts_type(base, "scalar") + "[]"
    if base in enums:
        return f'Database["public"]["Enums"]["{base}"]'
    if base in ("uuid", "text", "citext", "bpchar", "varchar", "char", "timestamptz", "timestamp", "date", "time", "inet", "bytea"):
        return "string"
    if base in ("int2", "int4", "int8", "numeric", "float4", "float8", "oid"):
        return "number"
    if base == "bool":
        return "boolean"
    if base in ("json", "jsonb"):
        return "Json"
    return "unknown"

def columns(relname, kind):
    rows = q(f"""select column_name, udt_name, data_type, is_nullable, column_default is not null, is_identity, identity_generation, is_generated
      from information_schema.columns where table_schema = 'public' and table_name = '{relname}' order by ordinal_position""").splitlines()
    cols = []
    for r in rows:
        name, udt, dtype, nullable, has_default, is_identity, ident_gen, is_generated = r.split("|")
        t = ts_type(udt, dtype)
        if nullable == "YES":
            t += " | null"
        cols.append({"name": name, "type": t, "nullable": nullable == "YES", "default": has_default == "t",
                     "identity_always": ident_gen == "ALWAYS", "generated": is_generated == "ALWAYS"})
    return cols

def relationships(relname):
    rows = q(f"""select con.conname, a.attname, cl2.relname, a2.attname, (select count(*) from pg_index i where i.indrelid = con.conrelid and i.indisunique and i.indkey::int2[] = con.conkey) > 0
      from pg_constraint con
      join pg_class cl on cl.oid = con.conrelid join pg_namespace n on n.oid = cl.relnamespace
      join pg_class cl2 on cl2.oid = con.confrelid
      join pg_attribute a on a.attrelid = con.conrelid and a.attnum = any(con.conkey)
      join pg_attribute a2 on a2.attrelid = con.confrelid and a2.attnum = any(con.confkey)
      where con.contype = 'f' and n.nspname = 'public' and cl.relname = '{relname}' and cl2.relnamespace = n.oid
      order by 1""").splitlines()
    rels = []
    for r in rows:
        if not r: continue
        name, col, ref, refcol, one = r.split("|")
        rels.append(f'{{ foreignKeyName: "{name}"; columns: ["{col}"]; isOneToOne: {"true" if one == "t" else "false"}; referencedRelation: "{ref}"; referencedColumns: ["{refcol}"] }}')
    return rels

tables = q("select table_name from information_schema.tables where table_schema='public' and table_type='BASE TABLE' order by 1").splitlines()
views = q("select table_name from information_schema.views where table_schema='public' order by 1").splitlines()

out = []
out.append("// Generated by scripts/generate-db-types.py. Do not edit by hand.")
out.append("export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\n")
out.append("export type Database = {")
out.append("  public: {")
out.append("    Tables: {")
for t in tables:
    cols = columns(t, "table")
    out.append(f"      {t}: {{")
    out.append("        Row: {")
    for c in cols: out.append(f'          {c["name"]}: {c["type"]};')
    out.append("        };")
    out.append("        Insert: {")
    for c in cols:
        if c["identity_always"] or c["generated"]: continue
        opt = "?" if (c["nullable"] or c["default"]) else ""
        out.append(f'          {c["name"]}{opt}: {c["type"]};')
    out.append("        };")
    out.append("        Update: {")
    for c in cols:
        if c["identity_always"] or c["generated"]: continue
        out.append(f'          {c["name"]}?: {c["type"]};')
    out.append("        };")
    rels = relationships(t)
    out.append("        Relationships: [" + ("" if not rels else "\n          " + ",\n          ".join(rels) + "\n        ") + "];")
    out.append("      };")
out.append("    };")
out.append("    Views: {")
for v in views:
    cols = columns(v, "view")
    out.append(f"      {v}: {{")
    out.append("        Row: {")
    for c in cols: out.append(f'          {c["name"]}: {c["type"]};')
    out.append("        };")
    out.append("        Relationships: [];")
    out.append("      };")
out.append("    };")

# Functions in public schema
out.append("    Functions: {")
fns = q("""select p.proname, pg_get_function_arguments(p.oid), pg_get_function_result(p.oid), p.proretset
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' order by 1""").splitlines()
def sql_ts(t):
    t = t.strip()
    if t.startswith("public."):
        t = t.split(".")[1]
    if t in enums: return f'Database["public"]["Enums"]["{t}"]'
    if t in tables: return f'Database["public"]["Tables"]["{t}"]["Row"]'
    m = {"uuid": "string", "text": "string", "timestamp with time zone": "string", "date": "string", "integer": "number", "boolean": "boolean", "jsonb": "Json", "void": "undefined", "bigint": "number", "numeric": "number"}
    return m.get(t, "unknown")
for f in fns:
    if not f: continue
    name, args, result, retset = f.split("|")
    out.append(f"      {name}: {{")
    if args:
        out.append("        Args: {")
        for a in args.split(", "):
            parts = a.split(" DEFAULT ")
            decl = parts[0].split(" ", 1)
            aname = decl[0].lstrip("_")
            atype = sql_ts(decl[1])
            opt = "?" if len(parts) > 1 else ""
            out.append(f"          {decl[0]}{opt}: {atype};")
        out.append("        };")
    else:
        out.append("        Args: Record<PropertyKey, never>;")
    if result.startswith("TABLE("):
        inner = result[6:-1]
        fields = []
        for c in inner.split(", "):
            cname, ctype = c.split(" ", 1)
            fields.append(f"{cname}: {sql_ts(ctype)} | null")
        out.append("        Returns: { " + "; ".join(fields) + " }[];")
    elif result.startswith("SETOF "):
        out.append(f"        Returns: {sql_ts(result[6:])}[];")
    else:
        out.append(f"        Returns: {sql_ts(result)};")
    out.append("      };")
out.append("    };")
out.append("    Enums: {")
for e, labels in enums.items():
    out.append(f"      {e}: " + " | ".join(json.dumps(l) for l in labels) + ";")
out.append("    };")
out.append("    CompositeTypes: { [_ in never]: never };")
out.append("  };")
out.append("};\n")
out.append('''type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type Views<T extends keyof PublicSchema["Views"]> = PublicSchema["Views"][T]["Row"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];
export type Functions<T extends keyof PublicSchema["Functions"]> = PublicSchema["Functions"][T];''')
print("\n".join(out))
